services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
    